apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    alertmanager:
      enabled: true
      enableAlertmanagerConfig: true
    prometheus:
      retention: 90d
      retentionSize: 9Gi
      volumeClaimTemplate:
        spec:
          storageClassName: px-csi-db
          resources:
            requests:
              storage: 10Gi
