- name: Get alertmanager-user-workload secret
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    kind: Secret
    name: alertmanager-user-workload
    namespace: openshift-user-workload-monitoring
  register: am_secret

- name: Decode alertmanager.yaml content
  set_fact:
    decoded_alertmanager: "{{ am_secret.resources[0].data['alertmanager.yaml'] | b64decode }}"

- name: Write decoded alertmanager.yaml to temp file
  copy:
    dest: /tmp/alertmanager.yaml
    content: "{{ decoded_alertmanager }}"
  delegate_to: localhost

- name: Ensure templates section is present
  blockinfile:
    path: /tmp/alertmanager.yaml
    block: |
      "templates":
      - "/etc/alertmanager/config/*.tmpl"
    marker: "# {mark} ANSIBLE MANAGED TEMPLATE BLOCK"
    insertafter: EOF
  delegate_to: localhost

- name: Re-encode updated alertmanager.yaml
  shell: base64 /tmp/alertmanager.yaml | tr -d '\n'
  register: encoded_alertmanager
  delegate_to: localhost

- name: Read Portworx email template content
  slurp:
    src: roles/px_prometheus_config/files/pxc_template.tmpl
  register: pxc_template_data
  delegate_to: localhost

- name: Get current alertmanager-user-workload secret again
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    kind: Secret
    namespace: openshift-user-workload-monitoring
    name: alertmanager-user-workload
  register: existing_secret

- name: Combine alertmanager.yaml and Portworx template into secret data
  set_fact:
    updated_secret_data: >-
      {{
        existing_secret.resources[0].data |
        combine({
          'alertmanager.yaml': encoded_alertmanager.stdout,
          'pxc_template.tmpl': pxc_template_data.content
        })
      }}

- name: Patch alertmanager secret with updated data
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: openshift-user-workload-monitoring
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: alertmanager-user-workload
      data: "{{ updated_secret_data }}"
    state: present

